package com.mygdx.game;

import com.badlogic.gdx.utils.Json;
import com.badlogic.gdx.utils.JsonValue;

public class Consumable{

    private int ID = -1;
    private String name, description;
    private consumeType type;
    private int power;

    public Consumable(String name, String description, consumeType type, int power) {
        this.name = name;
        this.description = description;
        this.type = type;
        this.power = power;
    }
    /**
     * Empty constructor required for class to be generated by deserialising json.
     */
    public Consumable(){}


    public void updateID(int id) {
        this.ID = id;
    }

    public enum consumeType {
        HEAL, REVIVE, MANAHEAL, SPEEDBUFF, STRENGTHBUFF, DEXTERITYBUFF, INTELLIGENCEBUFF;
    }


    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public consumeType getType() {
        return type;
    }

    public int getPower() {
        return power;
    }

    @Override
    public String toString() {
        return "Consumable{" +
                "ID=" + ID +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", type=" + type +
                ", power=" + power +
                '}';
    }
}
